name: Deploy to Vercel

on: 
  push:
    branches:
      - main
env: 
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Vercel
        id: install-vercel
        run: |
          npm install -g vercel
        
      - name: Pull Vercel config
        id: pull-vercel-config
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build app
        id: build-app
        run: |
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        id: deploy-to-vercel
        run: |
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}